include config

CXX=$(GCCDIR)/bin/$(TARGET)-g++
CC=$(GCCDIR)/bin/$(TARGET)-gcc
AS=$(GCCDIR)/bin/$(TARGET)-as
AR=$(GCCDIR)/bin/$(TARGET)-ar
LD=$(GCCDIR)/bin/$(TARGET)-ld
OBJCOPY=$(GCCDIR)/bin/$(TARGET)-objcopy
RANLIB=$(GCCDIR)/bin/$(TARGET)-ranlib
STRIP=$(GCCDIR)/bin/$(TARGET)-strip

EXEPREFIX=$(CROSSDIR)/bin/$(TARGET)
GDB=$(EXEPREFIX)-gdb

VDISK=/tmp/kos.img
ISO=/tmp/kos.iso
USBDEV=/dev/sdb
IMAGE=$(ISO)
QEMU_BASE=qemu-system-x86_64 -m 1024 -smp cores=2,threads=1,sockets=1 \
	-debugcon file:/tmp/KOS.dbg

#QEMU_BASE+=-d int,cpu_reset
#QEMU=$(QEMU_BASE) -hda $(VDISK)
QEMU=$(QEMU_BASE) -cdrom $(ISO) -serial file:/tmp/KOS.serial
QEMURGDB=$(QEMU_BASE) -cdrom $(ISO) -serial tcp::2345,server

KERNBASE=0xFFFFFFFF80000000
BOOTMEM=0x600000
BOOT16=0x1000

CFGFLAGS=-I. -D__KOS__ -m64\
	-DKERNBASE=$(KERNBASE) -DBOOTMEM=$(BOOTMEM) -DBOOT16=$(BOOT16)

DBGFLAGS=-g

#OPTFLAGS=-O2

LANGFLAGS=-std=c++11 -fno-exceptions -fno-rtti

COMPFLAGS=-fno-common -Wall -Wextra -Wno-unused-function -Wno-unused-parameter

MACHFLAGS=-ffreestanding -mcmodel=kernel -mno-red-zone\
	-mno-mmx -mno-sse -mno-sse2 -mno-sse3 -mno-3dnow

TSTFLAGS=$(CFGFLAGS) $(OPTFLAGS) $(DBGFLAGS) $(LANGFLAGS) $(COMPFLAGS)
PREFLAGS=$(CFGFLAGS) $(OPTFLAGS)             $(LANGFLAGS) $(COMPFLAGS) $(MACHFLAGS)
CXXFLAGS=$(CFGFLAGS) $(OPTFLAGS) $(DBGFLAGS) $(LANGFLAGS) $(COMPFLAGS) $(MACHFLAGS)
CFLAGS=              $(OPTFLAGS) $(DBGFLAGS)              $(COMPFLAGS) $(MACHFLAGS)

ASFLAGS=-g --64 --divide

ASFLAGS_BOOT=$(ASFLAGS) --defsym KERNBASE=$(KERNBASE)\
	--defsym BOOTMEM=$(BOOTMEM) --defsym BOOT16=$(BOOT16)

LDFLAGS=--defsym=KERNBASE=$(KERNBASE) --defsym=BOOTMEM=$(BOOTMEM) -static\
	-L$(GCCDIR)/$(TARGET)/lib -lstdc++ -lc -lelf\
	-L$(GCCDIR)/lib/gcc/$(TARGET)/$(GCCVER) -lgcc
#LDFLAGS+=-nostartfiles # only with gcc/g++ as linker
