include $(SRCDIR)/../config

GCC=$(GCCDIR)/bin/$(TARGET)-gcc
CC=$(GCC)
ifeq ($(CC),clang)
CXX=clang++
else
CXX=$(GCCDIR)/bin/$(TARGET)-g++
endif

AS=$(GCCDIR)/bin/$(TARGET)-as
AR=$(GCCDIR)/bin/$(TARGET)-ar
LD=$(GCCDIR)/bin/$(TARGET)-ld
RANLIB=$(GCCDIR)/bin/$(TARGET)-ranlib
STRIP=$(GCCDIR)/bin/$(TARGET)-strip

EXEPREFIX=$(CROSSDIR)/bin/$(TARGET)
GDB=$(EXEPREFIX)-gdb

VDISK=/tmp/KOS.img
ISO=/tmp/KOS.iso
USBDEV=/dev/sdX
IMAGE=$(ISO)
QEMU_BASE=$(TOOLSDIR)/bin/qemu-system-x86_64 -nodefconfig -display sdl\
	-m 768 -smp cores=4,threads=1,sockets=1 -debugcon file:/tmp/KOS.dbg

#QEMU_BASE+=-d int,cpu_reset
#QEMU=$(QEMU_BASE) -boot order=c -hda $(VDISK)
QEMU=$(QEMU_BASE) -boot order=d -cdrom $(ISO) -serial file:/tmp/KOS.serial
QEMUPXE=$(QEMU_BASE) -boot order=n -net nic\
	-net user,tftp=/tftpboot2,bootfile=pxelinux.0
QEMURGDB=$(QEMU_BASE) -cdrom $(ISO) -serial tcp::2345,server

KERNBASE=0xFFFFFFFF80000000
BOOTMEM=0x600000
BOOT16=0x1000

CLANGFLAGS=-target $(TARGET) -I$(GCCDIR)/$(TARGET)/include\
	-I$(GCCDIR)/$(TARGET)/include/c++/$(GCCVER)\
	-I$(GCCDIR)/$(TARGET)/include/c++/$(GCCVER)/$(TARGET)\
	-I$(GCCDIR)/lib/gcc/$(TARGET)/$(GCCVER)/include\
	-nostdinc++ -Wno-unused-private-field

CFGFLAGS=-I. -D__KOS__ -m64\
	-DKERNBASE=$(KERNBASE) -DBOOTMEM=$(BOOTMEM) -DBOOT16=$(BOOT16)

DBGFLAGS=-g

OPTFLAGS=-O3 -fno-omit-frame-pointer

LANGFLAGS=-std=c++11 -fno-exceptions -fno-rtti

COMPFLAGS=-fno-common -Wall -Wextra -Wno-unused-function -Wno-unused-parameter

ifeq ($(CC),clang)
COMPFLAGS+=$(CLANGFLAGS)
endif

MACHFLAGS=-ffreestanding -mcmodel=kernel -mno-red-zone\
	-mno-mmx -mno-sse -mno-sse2 -mno-sse3 -mno-3dnow

TSTFLAGS=$(CFGFLAGS) $(OPTFLAGS) $(DBGFLAGS) $(LANGFLAGS) $(COMPFLAGS)
PREFLAGS=$(CFGFLAGS) $(OPTFLAGS)             $(LANGFLAGS) $(COMPFLAGS) $(MACHFLAGS)
CXXFLAGS=$(CFGFLAGS) $(OPTFLAGS) $(DBGFLAGS) $(LANGFLAGS) $(COMPFLAGS) $(MACHFLAGS)
CFLAGS=              $(OPTFLAGS) $(DBGFLAGS)              $(COMPFLAGS) $(MACHFLAGS)

ASFLAGS=-g --64 --divide

ASFLAGS_BOOT=$(ASFLAGS) --defsym KERNBASE=$(KERNBASE)\
	--defsym BOOTMEM=$(BOOTMEM) --defsym BOOT16=$(BOOT16)

LDFLAGS=--defsym=KERNBASE=$(KERNBASE) --defsym=BOOTMEM=$(BOOTMEM) -static\
	-L$(GCCDIR)/$(TARGET)/lib -lstdc++ -lc -lelf\
	-L$(GCCDIR)/lib/gcc/$(TARGET)/$(GCCVER) -lgcc
#LDFLAGS+=-nostartfiles # only with gcc/g++ as linker
